#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: openjdk:17-alpine

options:
  docker: true

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - gradle
          script:
            - ./gradlew build
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
    - step:
        name: Deployment to DockerHub
        deployment: DockerHub
        script:
          - echo "Deploying to DockerHub"
          - export IMAGE_NAME=walshdanny700/campaign_optimisation
          - ./gradlew bootBuildImage --imageName=$IMAGE_NAME
          - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
          - docker push $IMAGE_NAME