name: Gradle Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Gradle build
      run: ./gradlew clean build --scan
    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: Test report
        path: build/reports/tests/test
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2.5.0
      with:
        generate-branches-badge: true
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv