name: Docker Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Gradlew Build Image
        run: ./gradlew bootBuildImage --imageName=walshdanny700/campaign_optimisation
      - name: Push To DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/campaign_optimisation